### ISSUE TITLE
O-18: distarray documentation

### ISSUE THREAD

**Issue by kwmsmith** [enthought/distarray#198]
Objective: To document the ODIN user-facing APIs, sufficient for a user familiar with
NumPy to be able to effectively use ODIN for distributed array computing.

Relevance: Comprehensive documentation for ODIN will ensure that new and existing users will be able to maximally benefit from ODIN’s capabilities.

Description: ODIN documentation will include: Beginner’s tutorials, worked examples, global and local API references and documentation, and (optionally) documentation of ODIN’s design and architecture.

**Comment by bgrant** [comment]
I would call this one done.  We have a functioning website, which can always be improved.  We have specific issues open for a couple of website issues.

A pass through the API docs will be done as part of the 0.6 release (#586).
