### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by kwmsmith** [enthought/distarray#394]
We need a simple website that gives distarray some curb appeal.  Even just a single page hosted by gh-pages with links to the repo, documentation, and other relevant stuff would be a great first start.

I really like the style of igraph's webpage:

    http://igraph.org/c/

Suggestions for other looks are welcome, of course.

**Comment by bgrant** [comment]
This one's done at a general level.  There's another issue for 

* images and figures showing what's possible and nice performance scaling (#596).

We can make more specific issues for other things.

Closing.
